import type { MarketplaceCatalogItem, MarketplaceStoredState } from "@/modules/marketplace-center/model/types";

export const MARKETPLACE_STORAGE_KEY = "tiy-agent-marketplace";
export const MARKETPLACE_ACTIVE_TAB_STORAGE_KEY = "tiy-agent-marketplace-active-tab";

export const MARKETPLACE_CATALOG: ReadonlyArray<MarketplaceCatalogItem> = [
  {
    id: "skill-ai-sdk",
    tab: "skills",
    name: "AI SDK Builder",
    summary: "Bootstrap generateText, streamText, tools, and chat UI flows faster.",
    description:
      "A practical starter skill for building agent features with streaming output, tool calling, and structured results. It focuses on production-shaped patterns instead of toy snippets.",
    publisher: "Tiy Official",
    version: "1.4.2",
    tags: ["Vercel AI SDK", "Tool Calling", "Streaming"],
    recommended: true,
    icon: "sparkles",
    sourceLabel: "Official catalog",
  },
  {
    id: "skill-docs-sync",
    tab: "skills",
    name: "Project Docs Sync",
    summary: "Keep README and agent instructions aligned with feature changes.",
    description:
      "Scans recent changes and proposes surgical documentation updates for root-level docs. Useful when feature work changes commands, architecture, or user-facing capabilities.",
    publisher: "Tiy Official",
    version: "0.1.0",
    tags: ["Documentation", "Automation"],
    recommended: true,
    icon: "books",
    sourceLabel: "Official catalog",
  },
  {
    id: "skill-github-flow",
    tab: "skills",
    name: "GitHub Flow Assistant",
    summary: "Guides issue triage, PR drafting, and release hygiene in one flow.",
    description:
      "Adds structured prompts and task framing for issue updates, pull request reviews, and release-note preparation. It is tuned for daily repository operations instead of raw API usage.",
    publisher: "Open Tools Lab",
    version: "2.0.1",
    tags: ["GitHub", "Review", "Release"],
    recommended: true,
    icon: "git-branch",
    sourceLabel: "Community verified",
  },
  {
    id: "skill-ui-audit",
    tab: "skills",
    name: "UI Audit Kit",
    summary: "Review spacing, state coverage, and frontend regressions before ship.",
    description:
      "Packages a review workflow for interaction states, responsive polish, and visual regression hotspots. It is optimized for desktop-class surfaces and production UI checks.",
    publisher: "Design Systems Guild",
    version: "0.9.7",
    tags: ["Frontend", "Review", "Accessibility"],
    recommended: false,
    icon: "layout",
    sourceLabel: "Community verified",
  },
  {
    id: "skill-rag-bootstrap",
    tab: "skills",
    name: "Local RAG Bootstrap",
    summary: "Set up embeddings, retrieval, and prompt assembly for local docs.",
    description:
      "A pragmatic starter for repo-grounded retrieval workflows using chunking, embeddings, and answer synthesis. It focuses on minimum viable architecture and evaluation hooks.",
    publisher: "Knowledge Forge",
    version: "1.2.0",
    tags: ["RAG", "Embeddings", "Search"],
    recommended: true,
    icon: "search",
    sourceLabel: "Partner catalog",
  },
  {
    id: "skill-bug-repro",
    tab: "skills",
    name: "Bug Repro Runner",
    summary: "Turn vague issue reports into reproducible debugging sequences.",
    description:
      "Helps structure environment capture, repro narrowing, and suspected root-cause notes. It is aimed at reducing wasted cycles during issue triage and verification.",
    publisher: "Debug Commons",
    version: "1.0.3",
    tags: ["Debugging", "Triage", "QA"],
    recommended: false,
    icon: "bug",
    sourceLabel: "Community verified",
  },
  {
    id: "mcp-filesystem",
    tab: "mcps",
    name: "Filesystem Bridge",
    summary: "Read and inspect workspace files through a scoped local MCP server.",
    description:
      "Provides high-signal file browsing, reading, and path-aware context for local projects. Best suited for repository-grounded coding workflows with strict workspace boundaries.",
    publisher: "Tiy Official",
    version: "1.1.0",
    tags: ["Filesystem", "Local", "Workspace"],
    recommended: true,
    icon: "folder",
    sourceLabel: "Official catalog",
  },
  {
    id: "mcp-github",
    tab: "mcps",
    name: "GitHub MCP",
    summary: "Issues, pull requests, search, and file operations from one server.",
    description:
      "Brings repository search, issue management, branch operations, and pull request workflows into the agent runtime. It is shaped for non-interactive coding flows and review automation.",
    publisher: "Tiy Official",
    version: "2.3.4",
    tags: ["GitHub", "PR", "Issues"],
    recommended: true,
    icon: "git-branch",
    sourceLabel: "Official catalog",
  },
  {
    id: "mcp-brave",
    tab: "mcps",
    name: "Brave Search",
    summary: "Recent web search and local place discovery for live verification.",
    description:
      "Adds general web search and local business discovery when questions need current or niche information. Designed for agent workflows that must verify unstable facts before answering.",
    publisher: "Partner Network",
    version: "1.8.1",
    tags: ["Search", "Web", "Local"],
    recommended: true,
    icon: "globe",
    sourceLabel: "Partner catalog",
  },
  {
    id: "mcp-postgres",
    tab: "mcps",
    name: "Postgres Inspector",
    summary: "Inspect schemas, tables, and queries without leaving the workbench.",
    description:
      "Surfaces schema metadata and query-friendly context for live PostgreSQL environments. Useful for planning data changes, debugging migrations, and validating application assumptions.",
    publisher: "Data Plane",
    version: "0.8.9",
    tags: ["Database", "Schema", "SQL"],
    recommended: false,
    icon: "database",
    sourceLabel: "Community verified",
  },
  {
    id: "mcp-chrome",
    tab: "mcps",
    name: "Chrome DevTools",
    summary: "Inspect DOM, console, network, and performance from the assistant.",
    description:
      "Provides page automation, snapshots, network introspection, and targeted performance traces. It is ideal for debugging frontend issues without manually bouncing between tools.",
    publisher: "Tiy Official",
    version: "1.6.0",
    tags: ["Browser", "DOM", "Performance"],
    recommended: true,
    icon: "chrome",
    sourceLabel: "Official catalog",
  },
  {
    id: "mcp-redis",
    tab: "mcps",
    name: "Redis Observer",
    summary: "Trace keys, streams, and cache state for runtime debugging.",
    description:
      "Gives agents a focused way to inspect Redis-backed queues, cache entries, and ephemeral state. It helps connect runtime behavior with backend assumptions during debugging.",
    publisher: "Data Plane",
    version: "0.6.4",
    tags: ["Redis", "Cache", "Queue"],
    recommended: false,
    icon: "server",
    sourceLabel: "Community verified",
  },
  {
    id: "mcp-context7",
    tab: "mcps",
    name: "Context7 Docs",
    summary: "Pull current library docs and examples directly into implementation workflows.",
    description:
      "Provides up-to-date documentation lookup for frameworks, SDKs, and libraries so agents can ground code generation in current APIs. Best suited for implementation tasks that depend on fast doc verification.",
    publisher: "Partner Network",
    version: "1.2.6",
    tags: ["Docs", "Libraries", "Implementation"],
    recommended: true,
    icon: "books",
    sourceLabel: "Partner catalog",
  },
  {
    id: "plugin-terminal-plus",
    tab: "plugins",
    name: "Terminal Plus",
    summary: "Adds richer terminal presets, command history pins, and quick snippets.",
    description:
      "Extends the embedded terminal with saved command snippets, task presets, and recent-command recall. Useful for repetitive repository workflows and local debugging loops.",
    publisher: "Tiy Official",
    version: "1.0.0",
    tags: ["Terminal", "Snippets", "Productivity"],
    recommended: true,
    icon: "terminal",
    sourceLabel: "Official catalog",
  },
  {
    id: "plugin-markdown-export",
    tab: "plugins",
    name: "Markdown Exporter",
    summary: "Export threads, plans, and review notes into portable Markdown bundles.",
    description:
      "Packages conversation output, structured plans, and review findings into clean Markdown documents. It is designed for handoff, archive, and async collaboration workflows.",
    publisher: "Tiy Official",
    version: "0.7.5",
    tags: ["Export", "Markdown", "Sharing"],
    recommended: true,
    icon: "box",
    sourceLabel: "Official catalog",
  },
  {
    id: "plugin-figma-connect",
    tab: "plugins",
    name: "Figma Connect",
    summary: "Attach design references and component notes to implementation tasks.",
    description:
      "Keeps design references, handoff notes, and component usage hints close to the implementation surface. It is intended for design-to-code workflows across product teams.",
    publisher: "Design Systems Guild",
    version: "1.3.2",
    tags: ["Design", "Figma", "Handoff"],
    recommended: true,
    icon: "layout",
    sourceLabel: "Community verified",
  },
  {
    id: "plugin-release-notes",
    tab: "plugins",
    name: "Release Notes Composer",
    summary: "Build release summaries from issues, commits, and merged pull requests.",
    description:
      "Aggregates repository activity into human-readable release notes with concise grouping and changelog framing. Best used near milestone close-out and patch releases.",
    publisher: "Open Tools Lab",
    version: "0.9.1",
    tags: ["Release", "Changelog", "GitHub"],
    recommended: false,
    icon: "workflow",
    sourceLabel: "Partner catalog",
  },
  {
    id: "plugin-tray-notifier",
    tab: "plugins",
    name: "Tray Notifier",
    summary: "Push background task updates into subtle desktop notifications.",
    description:
      "Turns long-running checks, review tasks, and background refresh events into unobtrusive desktop notifications. Intended for users who multitask across multiple windows.",
    publisher: "Tiy Labs",
    version: "0.5.8",
    tags: ["Notifications", "Desktop", "Background"],
    recommended: false,
    icon: "plug",
    sourceLabel: "Experimental channel",
  },
  {
    id: "plugin-workspace-snapshots",
    tab: "plugins",
    name: "Workspace Snapshots",
    summary: "Capture and restore lightweight workspace state presets on demand.",
    description:
      "Saves named workspace presets such as panel states, preferred tools, and quick-launch task contexts. It is helpful when switching between review, coding, and release modes.",
    publisher: "Tiy Labs",
    version: "0.4.3",
    tags: ["Workspace", "Presets", "State"],
    recommended: true,
    icon: "workflow",
    sourceLabel: "Experimental channel",
  },
  {
    id: "plugin-command-center",
    tab: "plugins",
    name: "Command Center",
    summary: "Launch saved workspace actions, scripts, and agent presets from one palette.",
    description:
      "Adds a compact command palette for saved workflows, common repo scripts, and reusable agent presets. It is designed to reduce repetitive navigation when switching between coding, review, and release tasks.",
    publisher: "Tiy Labs",
    version: "0.6.1",
    tags: ["Commands", "Palette", "Workflow"],
    recommended: true,
    icon: "sparkles",
    sourceLabel: "Experimental channel",
  },
];

export const DEFAULT_MARKETPLACE_STATE: MarketplaceStoredState = {
  "skill-docs-sync": { installed: true, enabled: true },
  "skill-bug-repro": { installed: true, enabled: false },
  "skill-ui-audit": { installed: true, enabled: false },
  "mcp-postgres": { installed: true, enabled: false },
  "mcp-github": { installed: true, enabled: true },
  "mcp-brave": { installed: true, enabled: false },
  "plugin-terminal-plus": { installed: true, enabled: true },
  "plugin-markdown-export": { installed: true, enabled: true },
  "plugin-release-notes": { installed: true, enabled: false },
};
